name: version-sync
description: This repository is for trying version migration

branding:
  icon: airplay
  color: yellow

inputs:                                            # stack inputs 
  - name: NODE_VERSION                             # stack input name
    default: v12.22.4                                 # default value
    description: Node version for the Node.js stack   # description
    validvalues:                                      # values that can be selected
    - v12.22.4
    - v14.17.4
    
configs:
  repo-metadata:
    parameters:
      description: 'A react-app template'
      topics:
        - react-app
        - nodejs
        - vercel
init:
  uses: stack-init.yaml
